[project]
authors = ["yakmanyakmanyedatsme <wfrancis@fordham.edu>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "hello-world-nightly"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0.dev2024091405,<25"
