[project]
authors = ["yakmanyakmanyedatsme <wfrancis@fordham.edu>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "hello-world-nightly"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.3.0,<26"
max-pipelines = ">=25.3.0,<26"
